window.acts = [
  {
    type: 'theater',
    name: 'Gypsi Swing Dance',
    details: "Swingingpool Zürich, Hellzapoppin' Disaster",
    youtubeID: 'P6FyhtZHXCE',
  },
  {
    type: 'concert',
    name: 'Donnergroll und Bienensumm',
    details: "A la Q'Art",
    youtubeID: '96trcjsIHso',
  },
  {
    type: 'theater',
    name: 'Frau Meier, die Amsel',
    details: 'Figurentheater Lupine',
    youtubeID: '324CYS2I_a0',
  },
  {
    type: 'concert',
    name: 'Wechselspiel',
    details: 'Harmonie Eintracht Küsnacht',
    youtubeID: 'P2nMTsZr2bU',
  },
  {
    type: 'concert',
    name: 'Orgelinspirationen',
    details: 'Christer Løvold',
    youtubeID: 'EBinIWchpm8',
  },
  {
    type: 'exhibition',
    name: 'Zu Besuch bei C.G. und Emma Jung',
    details: 'Eva Middendorp, Museum Haus C.G. Jung; Andreas Jung',
    youtubeID: 'S0d4bKmnurc',
  },
  {
    type: 'theater',
    name: 'Plaza Suite',
    details: 'Die Kulisse',
    youtubeID: 'l17c8sI7qDs',
  },
  {
    type: 'concert',
    name: 'Broadway',
    details: 'Fanfare Terrible',
    youtubeID: 'pOzO62pLdU0',
  },
  {
    type: 'theater',
    name: 'Seelchen - Tanzmärchen',
    details: 'Christina Maria Meyer, Hannah Galli, Musik: Aaron Wegmann und Mirjana Markovic',
    youtubeID: 'QAD8DgeKoIE',
  },
  {
    type: 'concert',
    name: 'Perlen der Sakralmusik',
    details: 'Vokalensemble St. Georg',
    youtubeID: 'KQzHJJJC0lg',
  },
  {
    type: 'theater',
    name: 'Actionpainting und Kunsthappening',
    details: 'Künstlerinnen und Künstler von Artischock',
    youtubeID: 'qC7G4k7HN0o',
  },
  {
    type: 'concert',
    name: 'Elements',
    details: 'Hiphop Zoo',
    youtubeID: '_Fnrryomm0I',
  },
  {
    type: 'poetry',
    name: 'Sprechende Dinge im Museum',
    details: 'Die Kulisse',
    youtubeID: 'BOmFEoQsLyc',
  },
  {
    type: 'concert',
    name: 'Lieder',
    details: 'Lea Gottheil',
    youtubeID: 'qDoM9Bm1wxE',
  },
  {
    type: 'exhibition',
    name: 'Malerei von HARUKO',
    details: 'HARUKO und NIMUE',
    youtubeID: 'lfsY03lwK14',
  },
  {
    type: 'poetry',
    name: 'Die Sprachgranate aus Zürich',
    details: 'Rebekka Lindauer',
    youtubeID: 'XclKvDxpyh0',
  },
  {
    type: 'exhibition',
    name: 'Schätze aus dem Bildarchiv',
    details: 'Ruth Ammann, Petra von Bechtolsheim, C.G. Jung-Institut',
    youtubeID: 'st7Zg_-MJJw',
  },
  {
    type: 'concert',
    name: 'Saxtett',
    details: 'Saxophon-Ensemble der Musikschule Küsnacht',
    youtubeID: 'X8D9AQlobCg',
  },
  {
    type: 'theater',
    name: 'Gewandschau - von schlichtelegant bis extravagant',
    details: 'Margrith Schlegel',
    youtubeID: 'ypnTD_zPPxA',
  },
  {
    type: 'concert',
    name: 'Klavierimprovi&shy;sationen über ein literarisches Thema',
    details: 'Martin Wettstein',
    youtubeID: 'NIlcU6LqyDE',
  },
];
